resilience4j:
  circuitbreaker:
    configs:
        default:
            sliding-window-size: 6
            failure-rate-threshold: 50
            wait-duration-in-open-state: 20s
            permitted-number-of-calls-in-half-open-state: 4
            slow-call-rate-threshold: 50
            slow-call-duration-threshold: 10s
    instances:
      products:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 20s
    instances:
      products:
        base-config: default

spring:
  cloud:
    gateway:
      routes:
      - id: products-service
        uri: lb://products-service
        predicates:
          - Path=/api/products/**
        filters:
          - StripPrefix=2  

          - name: CircuitBreaker
            args:
              name: products
              statusCodes: 500
              fallbackUri: forward:/api/items/detail/9/cantidad/3

          - name: Example
            args:
              message: Hola mi mensaje Personalizado
              cookie: user
              cookieValor: KevinPerez

      - id: item-service
        uri: lb://item-service
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2  
          - AddRequestHeader=token-request, 123456 
          - AddResponseHeader=token-response, 123456 
          - SetResponseHeader=Content-Type, application/json 
          - AddRequestParameter=name, kevin
      - id: config-server
        uri: lb://config-server
        predicates:
          - Path=/api/configuration/**
        filters:
          - StripPrefix=2  
      - id: security-oauth-service
        uri: lb://security-oauth-service
        predicates:
          - Path=/api/security/**
        filters:
          - StripPrefix=2  
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/api/users/**
        filters:
          - StripPrefix=2  
